[package]
name = "WebServer_Test"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.5"
futures = "0.3.8"
reqwest = "0.11"
tokio = { version = "1", features = ["full"] }
